// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMasterApi.Models;

namespace TaskMasterApi.Migrations
{
    [DbContext(typeof(TaskMasterApiContext))]
    [Migration("20181123083001_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TaskMasterApi.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseCode");

                    b.Property<string>("Title");

                    b.HasKey("CourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("TaskMasterApi.Models.Dodge", b =>
                {
                    b.Property<int>("DodgeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Reason");

                    b.Property<int?>("TopicId");

                    b.HasKey("DodgeId");

                    b.HasIndex("TopicId");

                    b.ToTable("Dodge");
                });

            modelBuilder.Entity("TaskMasterApi.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Confidence");

                    b.Property<int>("CourseId");

                    b.Property<string>("Title");

                    b.HasKey("TopicId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("TaskMasterApi.Models.WorkBlock", b =>
                {
                    b.Property<int>("WorkBlockId")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Time");

                    b.HasKey("WorkBlockId");

                    b.ToTable("Workblock");
                });

            modelBuilder.Entity("TaskMasterApi.Models.WorkSession", b =>
                {
                    b.Property<int>("WorkSessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<DateTime>("ScheduleAfter");

                    b.Property<int?>("TopicId");

                    b.HasKey("WorkSessionId");

                    b.HasIndex("TopicId");

                    b.ToTable("WorkSession");
                });

            modelBuilder.Entity("TaskMasterApi.Models.Dodge", b =>
                {
                    b.HasOne("TaskMasterApi.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("TaskMasterApi.Models.WorkSession", b =>
                {
                    b.HasOne("TaskMasterApi.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
                });
#pragma warning restore 612, 618
        }
    }
}
